Camera: Fix mismerge of Jellybean commit f773f0589761fba76ed4fb77345fb24efbce9828
If QCOM_ICS_COMPAT is defined build breaks with this error
frameworks/av/media/libstagefright/CameraSource.cpp:582:13: error:
'CAMERA_CMD_SET_VIDEO_BUFFER_COUNT' was not declared in this scope

Moved this new define outside of the ifdef to fix build

Change-Id: I5cc8bb164e61231a89a1ba8cffe78a91f0c8c7a7
Signed-off-by: dhacker29 <davidhackerdvm@gmail.com>